# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 821dd0a0a6b804c52f9a1efbda7e8ca526d8c7b47753ef8ff8c0750029fbae8d31b82dcdb4b18bed01e2ce4d06a61d38a657774b4e5a6ababac2eb480d66d3b8

test:
  secret_key_base: ae3dbf26bb9f0c5013ba50c95fe0c29ea672129532e8c1edcaf049fbd104b9eeb5fc2a13c498dc8416df56e13f7734750ecd0c044f60f5bdd63d90de8ce4ad0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
